-- USE DEDICATED WAREHOUSE FOR COMPUTE PURPOSES

USE WAREHOUSE CONVEX_INSURANCE;

-- CREATE TABLES FOR DATA WAREHOUSE / INFORMATION VAULT

USE "CONVEX_INSURANCE"."CONVEX_WAREHOUSE";

--- CREATE SCHEMA FOR DESIGNING THE FACTS AND DIMENSIONS - IDEALLY VIEWS FOR THIS CASE AS WE HAVE THE DATA VAULT BUILT

-- CREATE FACT TABLE

CREATE OR REPLACE VIEW FACT_TRANSACTIONS AS 
SELECT
  LT.HASH_LINK_TRANSACTION_ID AS DATA_WAREHOUSE_ID,
  LT.HASH_CUSTOMER_ID AS CUSTOMER_ID,
  LT.HASH_PRODUCT_ID AS PRODUCT_ID,
  ST.PRICE AS PRICE,
  ST.TRANSACTION_DATE
FROM
    CONVEX_VAULT.LINK_TRANSACTION LT
    JOIN CONVEX_VAULT.SAT_TRANSACTION ST
    ON LT.HASH_LINK_TRANSACTION_ID = ST.HASH_LINK_TRANSACTION_ID;
    
-- CREATE CUSTOMER DIMENSION 

CREATE OR REPLACE VIEW DIM_CUSTOMER AS
SELECT
    HC.HASH_CUSTOMER_ID AS CUSTOMER_ID,
    SC.LOYALTY_SCORE
FROM
    CONVEX_VAULT.HUB_CUSTOMER HC 
    JOIN CONVEX_VAULT.SAT_CUSTOMER SC 
    ON HC.HASH_CUSTOMER_ID = SC.HASH_CUSTOMER_ID;
    
--- CREATE PRODUCT DIMENSION

CREATE OR REPLACE VIEW DIM_PRODUCT AS
SELECT
    HP.HASH_PRODUCT_ID AS PRODUCT_ID,
    SP.PRODUCT_CATEGORY,
    SP.PRODUCT_DESCRIPTION
FROM
    CONVEX_VAULT.HUB_PRODUCT HP
    JOIN CONVEX_VAULT.SAT_PRODUCT SP
    ON HP.HASH_PRODUCT_ID = SP.HASH_PRODUCT_ID;